import { Container, Header } from '@/components/shared';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Корзина',
    description: 'Generated by create next app',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="min-h-screen bg-[#F4F1EE]">
            <Container>
                <Suspense>
                </Suspense>
                {children}
            </Container>
        </main>
    );
}
